# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.chucklecabinrecords.com
title: Chuckle Cabin Records
email: info@chucklecabinrecords.com
author: Chuckle Cabin Records
description: "Melbourne based standup comedy label"
includes: ["_pages"]

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:title/

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/chucklecabin
  - title: facebook
    url: https://www.facebook.com/ChuckleCabinRecords/
  - title: instagram
    url: https://www.instagram.com/chucklecabinrecords/
